### ISSUE TITLE
Hangs when passed an external URL which won't respond with a reasonable timeout

### ISSUE THREAD

**Issue by danielwestendorf** [westy92/html-pdf-chrome#115]
I've found that setting timeouts similar to those in the tests results in an error message as expected when an non-responding URL is provided. However, when the timeout is higher (10sec or so) no error is raised as expected. Given the following code:

```
const htmlPdf = require('html-pdf-chrome');
let options = { port: 9222, timeout: 100 };

htmlPdf.create('http://localhost:3904/', options).catch(console.error)
> Error: HtmlPdf.create() timed out.
```
This is as expected. However, when the timeout is higher...
```
const htmlPdf = require('html-pdf-chrome');
let options = { port: 9222, timeout: 10000 };

htmlPdf.create('http://localhost:3904/', options).catch(console.error)
```

No error is ever logged to the console.

Am I using the wrong configuration option here?

OS: macOS 10.13.2 (17C88)
Chrome: Google Chrome 63.0.3239.132
Node: v8.9.1

Edit: Add versions

**Comment by westy92** [comment]
An internal `_canceled` flag is set once the timeout is reached.  This flag is checked between each major step in the generation process, throwing a timeout error if necessary.

Is it possible that it's generating correctly in your second example?  Try capturing a `Promise` resolution as well, like this:
```ts
const htmlPdf = require('html-pdf-chrome');
let options = { port: 9222, timeout: 10000 };

htmlPdf.create('http://localhost:3904/', options)
  .then(console.log)
  .catch(console.error)
```

**Comment by danielwestendorf** [comment]
Thanks for the prompt response, definitely appreciated!

No, it definitely is not rendering, as there is no server running on that port.

I ran into this problem when I was trying to render a PDF for a server which was offline for whatever reason at the time of render, and the host + random port was just a way to boil down the issue to a repeatable state.

What else can I do to help identify what's going on? I tried adding a failing test to my fork of the project, but unfortunately I don't know enough about TS/Chai -- the test execution gets bypassed because of what I assume is the test suite's own timeout parameters.

    it('should timeout with an invalid URL', async () => {
      const options: HtmlPdf.CreateOptions = {
        port,
        timeout: 10000,
      };
      try {
        await HtmlPdf.create('http://127.0.0.1:34386/', options);
        expect.fail();
      } catch (err) {
        expect(err.message).to.equal('HtmlPdf.create() timed out.');
      }

    });

**Comment by westy92** [comment]
I have confirmed this.  For some reason, the underlying navigation code is reporting success.  I will look into this more.

**Comment by westy92** [comment]
This should now be fixed.  Instead, if a page cannot be reached, now `new Error('HtmlPdf.create() page navigate failed.')` should be thrown.
Once CI tests pass, I'll cut a fresh release.  Thank you!

**Comment by westy92** [comment]
[v0.4.2](https://github.com/westy92/html-pdf-chrome/releases/tag/v0.4.2) has been released.
