### ISSUE TITLE
Screenshot support

### ISSUE THREAD

**Issue by tomasc** [westy92/html-pdf-chrome#13]
Since all the infrastructure is already in it might be interesting to consider expanding this library to support output to other formats such as PNG or JPG in the future.

See for example
https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a
https://github.com/schnerd/chrome-headless-screenshots

**Comment by tomasc** [comment]
Another good starting point:
https://jonathanmh.com/taking-full-page-screenshots-headless-chrome

**Comment by rhyek** [comment]
What should this new API look like?

**Comment by westy92** [comment]
Implemented in https://github.com/westy92/html-pdf-chrome/pull/322 🎉
