### ISSUE TITLE
Footer is missing on first page?

### ISSUE THREAD

**Issue by scottdj92** [westy92/html-pdf-chrome#136]
I'm using this lib to convert a static page using React to a pdf for printing purposes.

I'm currently passing in a string with all of my styles inside of the footer. I can see it appearing on the second pages and the pages after that. What I don't see is the footer on the first page. I can still select the text on it, so I know it exists, but it seems to be covered with a white block.

Does Chrome have some sort of functionality that prevents the footer from appearing on the first page only?

Node.JS version: 8.9.3
Chrome version: 65.0.3325.181
html-pdf-chrome version: 0.5.0

**Comment by scottdj92** [comment]
The solution was that our main div element was being explicitly set as 11in tall, while our generated pdf was being generated as 11in. The div element would overlap with the footer (as it's not considered a part of the extracted HTML).

I solved this by increasing the marginBotton value in the createHTML options object.

**Comment by tashigarg** [comment]
@scottdj92 @westy92 
Hi, I am facing the similar issue while adding footer template. These are my node js options
const options = {
...
 printOptions: {
    marginTop: 1,
    marginBottom: 2,
    marginLeft: 1,
    marginRight: 1,
    printBackground: true,	
    displayHeaderFooter: true,
    footerTemplate: '<div style= "-webkit-print-color-adjust: exact;width:100%; height:50px;  background-color: #303030 !important;"><div style="color: #d6d6d6 !important;padding-top: 18px;font-family: Arial;font-size: 14px;"><div class="text left" style="float: left; margin-left:24px">Date: <span class="reportTime date"></span></div><div class="text right" id="pageNum" style="float: right;margin-right:10px">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div></span></div></div>',
  },
};

None of the margin options are making any impact. I have two pages on the html. The html div is still overlapping the pdf footer making it invisible. 
Page 1 footer:
![screen shot 2018-04-13 at 5 01 56 pm](https://user-images.githubusercontent.com/38350997/38732662-a1a8e8a8-3f3c-11e8-9f44-710b5f0793b1.png)

Last page footer:
![screen shot 2018-04-13 at 5 01 44 pm](https://user-images.githubusercontent.com/38350997/38732666-a69e6702-3f3c-11e8-88ee-d2fcb53c6830.png)

Can you please help how to fix these.

Thanks.
