### ISSUE TITLE
Feature request (Custom headers/footers)

### ISSUE THREAD

**Issue by os1r1s110** [westy92/html-pdf-chrome#16]
Is it possible to add custom header/footer? 

I searched for a way to do it using the chrome executable directly but they seem to point that it will be the responsibility of third party apps/libraries to implement it...

**Comment by westy92** [comment]
This library may help significantly: https://github.com/byuarchdi/print-headers-and-footers

**Comment by Exiliot** [comment]
@westy92 The bug, which this library is aimed to fix, is already fixed in Chrome:
![image](https://user-images.githubusercontent.com/4901187/33023963-67a8d226-ce12-11e7-9cf5-e646e27aefe2.png)
It seems that the requested feature is more related to [this one bug](https://bugs.chromium.org/p/chromium/issues/detail?id=368053).

**Comment by mingyugao** [comment]
I tried setting custom header and footer template parameters using [this](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF), but it didn't work. Really would love this feature!

**Comment by os1r1s110** [comment]
@mingyugao the "displayHeaderFooter"  in this case only enables/disables the default chrome header/footer (the page number, the source link I think and other information like this), it is not applicable to custom header/footer yet.

**Comment by westy92** [comment]
@mingyugao, I think using those new parameters may be our best bet!  I started some work [here](https://github.com/westy92/html-pdf-chrome/tree/custom-header-footer) but was unable to get it to work.  I made sure to use Chrome 64 but still had issues like the others here: https://github.com/GoogleChrome/puppeteer/issues/373.

**Comment by westy92** [comment]
I believe this is the relevant Chrome source: https://cs.chromium.org/chromium/src/components/printing/resources/print_preview_page.html?q=headerTemplate&sq=package:chromium&dr=C&l=69

**Comment by westy92** [comment]
Turns out that landed in [65.0.3294.0](https://storage.googleapis.com/chromium-find-releases-static/a2e.html#a2e8edb82a7be88bf29795cc0e6ef3930b9cb3d9).  I'm making some progress!

**Comment by os1r1s110** [comment]
What would be missing for it to be usable? Only updating the typings definitions or something else?

**Comment by westy92** [comment]
Primarily waiting for Chrome 65 to be promoted to the stable channel.
It looks like that could be as soon as March 6th. https://www.chromium.org/developers/calendar

**Comment by westy92** [comment]
@os1r1s110 @Exiliot @mingyugao Chrome 65 became stable today, so I cleaned up my branch. Any thoughts on my PR are welcome! Thank you.

**Comment by os1r1s110** [comment]
@westy92 Seems pretty good to me for header/footer template as supported by the dev tools! :)

**Comment by westy92** [comment]
I plan to do a release in a few hours. Thank you all for your patience!

**Comment by os1r1s110** [comment]
Thank you for publishing it, it's really nice to work with. 

Puppeteer works really well too but don't have a trivial option to run a single instance and reuse it as you do with this package :0

**Comment by westy92** [comment]
Released in [v0.5.0](https://github.com/westy92/html-pdf-chrome/releases/tag/v0.5.0). You're welcome!
