### ISSUE TITLE
CompletionTrigger waitUntil: "networkidle0"

### ISSUE THREAD

**Issue by jbustamovej** [westy92/html-pdf-chrome#168]
None of the completion triggers worked for my react app. I checked puppeteer's waitUntil: "networkidle0" and that worked for me. https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagegotourl-options

**Comment by laurentdebricon** [comment]
But how do you use it ?
inside a new htmlPdf.CompletionTrigger ?? how ?
thank you

**Comment by gytisgreitai** [comment]
yep, non of the completion triggers seems to work for me also... it just hangs forever until timeout

**Comment by westy92** [comment]
In the next release, you'll be able to use the `LifecycleEvent` `CompletionTrigger` to mimic `networkidle0` and `networkidle2`.

The mapping from Puppeteer to Chrome page lifecycle events is:

* `networkidle0` -> `networkIdle`
* `networkidle2` -> `networkAlmostIdle`
* `domcontentloaded` -> `DOMContentLoaded`

Usage:

```ts
import * as htmlPdf from 'html-pdf-chrome';

const html = '<p>Hello, world!</p>';
const options: htmlPdf.CreateOptions = {
  port: 9222, // port Chrome is listening on
  completionTrigger: new htmlPdf.CompletionTrigger.LifecycleEvent(
    'networkIdle', // name of the Chrome lifecycle event to listen for. Defaults to 'firstMeaningfulPaint'.
    5000 // optional timeout (milliseconds)
  ),
};

const pdf = await htmlPdf.create(html, options);
```
