### ISSUE TITLE
d3.js charts are not coming in printed pdf

### ISSUE THREAD

**Issue by developerKumar** [westy92/html-pdf-chrome#169]
Hi, I am using d3.js charts in my html. When I print pdf using html-pdf-chrome , then it only shows html. It does not render charts. Please help me.

**Comment by developerKumar** [comment]
[test.pdf](https://github.com/westy92/html-pdf-chrome/files/2270078/test.pdf)
`printBackground: true` didn't work.
below is required output.
![screenshot from 2018-08-08 17-07-47](https://user-images.githubusercontent.com/19240457/43834956-ae5a0d6e-9b2d-11e8-939e-06909d9b13a8.png)

**Comment by westy92** [comment]
It's possible that it is printing before rendering is complete. Are you using any completion triggers?

**Comment by developerKumar** [comment]
No i am not using completion triggers.

**Comment by westy92** [comment]
Try using one. An easy test would be using a timer one:
```typescript
completionTrigger: new htmlPdf.CompletionTrigger.Timer(5000)
```

**Comment by westy92** [comment]
Closing. If adding a CompletionTrigger did not fix the issue, please leave a comment with some reproducible sample code and I can investigate further.
