### ISSUE TITLE
background-color style not working as expected

### ISSUE THREAD

**Issue by sameerjain** [westy92/html-pdf-chrome#176]
I am having a very small issue, I have a simple div with following style set
 `style="background-color: #32b251"`
But this doesn't get rendered, all I can see is white background instead of green.

Thank you for your all the hard work you put into this, I was able to create complex pdf with bootstrapped style but just stuck with that there. If you can provide some help here would be great.

Thank You

**Comment by sameerjain** [comment]
After implementing `style="background-color: #32b251 !important"` it started drawing background but I now have a different issue, how can I make print everything on single page?

**Comment by adamreisnz** [comment]
Still not working with inline CSS.

**Comment by westy92** [comment]
@adamreisnz could you please attach some example HTML and CSS that isn't working?

**Comment by adamreisnz** [comment]
I had a simple div with a class, and applying a background colour to it that wasn't rendering. Inline style didn't help either. But the problem was not the rendering as it turns out, but rather the printBackground option that needed to be set to true.

**Comment by westy92** [comment]
Ah, thanks for the clarification! I'm glad `printBackground: true` fixed it. 👍
