### ISSUE TITLE
Add extra http header

### ISSUE THREAD

**Issue by StefftheEmperor** [westy92/html-pdf-chrome#198]
Is there a way to add a custom http header to the page request? In the CDP seems to be a method on the Network Object: Network.setExtraHTTPHeaders

thanks!

**Comment by westy92** [comment]
I just published [v0.6.0](https://github.com/westy92/html-pdf-chrome/releases/tag/v0.6.0) which now supports sending custom HTTP headers with a request!
https://github.com/westy92/html-pdf-chrome#http-headers
