### ISSUE TITLE
Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by venkadesh-p** [westy92/html-pdf-chrome#234]
I am getting this error (`Error: connect ECONNREFUSED::1:50296`) when I am using `create` function in node js. I couldn't find the issue, anyone please help me to fix this.

**Comment by westy92** [comment]
Make sure you have Chrome running and listening on the same port `html-pdf-chrome` is using.

**Comment by westy92** [comment]
I'm closing the issue because it's stale. Please add another comment if this issue resurfaces.
