### ISSUE TITLE
Vulnernable to SSRF when letting users convert custom html

### ISSUE THREAD

**Issue by vixriihi** [westy92/html-pdf-chrome#249]
This library is vulnerable to Server-Side Request Forgery (SSRF) when users can input the html being converted to pdf.

**Comment by skarger** [comment]
The NPM advisory for this causes `yarn audit` to fail, but there's no fix available. Preventing the server from fetching URLs would prevent the rendering of the PDF.

https://www.npmjs.com/advisories/1339

Is it possible to close this advisory? Or release a new version of this package as a workaround to satisfy `yarn audit`?

**Comment by westy92** [comment]
Version 0.6.1 has been released and I have included a [Security](https://github.com/westy92/html-pdf-chrome#security) section. I have pinged npm about the advisory.

**Comment by westy92** [comment]
The advisory has been removed from both npm and Snyk.
