### ISSUE TITLE
CSS conic-gradient issue

### ISSUE THREAD

**Issue by zsebalint** [westy92/html-pdf-chrome#295]
Hi, the conic-gradient css rule not working in the generated pdf 

```
.someClass {
  width: 100px; height: 100px;
  border-radius: 50%;
  background: conic-gradient(#655655 40deg, yellowgreen 0);
}
```
I've got a circle, but the coloring is not working. Can you help me? 
This option is not help:  printOptions: { printBackground: true }

**Comment by westy92** [comment]
I just tried this on macOS 11.3 and Chrome 90. The result worked as expected: [test.pdf](https://github.com/westy92/html-pdf-chrome/files/6424656/test.pdf)
![image](https://user-images.githubusercontent.com/290167/117087592-9293a480-ad15-11eb-83e2-d34447a7096f.png)
```typescript
const options: HtmlPdf.CreateOptions = {
  printOptions: {
    printBackground: true,
  },
};
const html = `
<html>
  <head>
    <style>
      .someClass {
        width: 100px; height: 100px;
        border-radius: 50%;
        background: conic-gradient(#655655 40deg, yellowgreen 0);
      }
    </style>
  </head>
  <body>
    <div class="someClass"></div>
  </body>
</html>
`;
const result = await HtmlPdf.create(html, options);
result.toFile('test.pdf');
```

**Comment by westy92** [comment]
If this is still an issue, please respond with a full code example.
