### ISSUE TITLE
PDF with searchable text

### ISSUE THREAD

**Issue by ftbol** [westy92/html-pdf-chrome#302]
Hi @westy92 Right now the generated (printed) PDF is like an image, with no searchable/selectable text, no hyperlinks etc'. 

Is there a way to make it as a regular PDF with a searchable text? 

Thanks

**Comment by westy92** [comment]
What you desire is working fine for me on macOS:

```typescript
const pdf = await HtmlPdf.create('<p>hello <a href="https://www.google.com">world</a>!</p>', {port});
pdf.toFile('test.pdf');
```

[test.pdf](https://github.com/westy92/html-pdf-chrome/files/6664695/test.pdf)

Our automated tests run on all supported platforms and [depend on searchable text to pass](https://github.com/westy92/html-pdf-chrome/blob/master/test/index.ts#L468).

Can you share a small, reproducible code sample?

**Comment by ftbol** [comment]
Thanks for the info.

We've tried more and apparently this one line of css cause that:

-webkit-filter: opacity(1);

So now we know how to solve it (or use it if needed.. This is now a feature :)

Examples attached.
[Demo.zip](https://github.com/westy92/html-pdf-chrome/files/6668466/Demo.zip)
