### ISSUE TITLE
Editable form field creation

### ISSUE THREAD

**Issue by GMacret** [westy92/html-pdf-chrome#309]
Hello,

I have an issue when trying to create a form in my pdf.
What I am currently doing is declaring a form field in html with text inputs. I do get  a rectangle on my render but however it is not editable and I can not get it using libs to edit pdf such as pdf-lib. It seems to be rendered as an image?

Is there any way to create editable form fields from an html file?

Thank you by advance

**Comment by westy92** [comment]
This is not possible since Chrome does not support this. Sorry!
