### ISSUE TITLE
HtmlPdf.create() connection lost

### ISSUE THREAD

**Issue by adamreisnz** [westy92/html-pdf-chrome#312]
Hi there, we're occasionally receiving this error from the library, which I presume relates to the connection with Chrome.
This in itself is not an issue, but what is a problem is that for some jobs that are suppose to generate a PDF, this error is thrown after about 4-5 hours into the job. Normally this job is supposed to take a few seconds.

Is there any way to specify a timeout so the whole process doesn't take more than say 60 seconds, and errors otherwise?

I know there is a completion callback/timeout, and we use that, but it doesn't seem to affect this particular case.
We also specify the port to an already running Chrome instance.

Here is a snippet of our code:

![image](https://user-images.githubusercontent.com/490562/140234869-03c7ecfe-5616-4953-ad5d-37ddecc5d2f2.png)

Are there any options that we can use that might help?

**Comment by adamreisnz** [comment]
Looking at the code, there appears to be a `timeout` option that is used, so I will give that a go:

https://github.com/westy92/html-pdf-chrome/blob/master/src/index.ts#L69

**Comment by westy92** [comment]
Yes, that should work!

**Comment by adamreisnz** [comment]
@westy92 Sorry just following up on this one, we are now quite frequently running into the `HtmlPdf.create() timed out` error instead. I suppose it's preferable over the connection lost after 4-5 hours, but just wondering what could cause the PDF generation to take so long?

We are only generating very small PDF files (1 single page or in some cases even just a badge/card format), and I don't quite understand why they would take more than 25 seconds to generate?

Anything I can do to analyse/debug this in more detail?

**Comment by adamreisnz** [comment]
I think in this case it was caused by some excessively large images that were being loaded.

**Comment by westy92** [comment]
Thank you for following up! These tips may help others in the future. :)
