### ISSUE TITLE
I made a server library for html-pdf-chrome

### ISSUE THREAD

**Issue by esbenp** [westy92/html-pdf-chrome#33]
Hey, 
Just wanted to say we (at [Traede](http://traede.com)) really appreciate your library. It has made our life a lot better these last few days :-)! We just open sourced our pdf server that uses html-pdf-chrome to generate PDFs. Thought you might be interested in seeing it. You can find it here [pdf-bot](https://github.com/esbenp/pdf-bot). Feedback is very welcome!

Let us now if we can help out with issues, we will try our best to help! Keep up the good work!

**Comment by westy92** [comment]
Great, thanks for sharing!  If you'd like to contribute, issues marked with "help wanted" are a great place to start. 😃
