### ISSUE TITLE
comparison with https://github.com/GoogleChrome/puppeteer ?

### ISSUE THREAD

**Issue by graingert** [westy92/html-pdf-chrome#36]
https://github.com/GoogleChrome/puppeteer

**Comment by westy92** [comment]
Puppeteer is a library similar to the one we use (chrome-remote-interface) to interface with Chrome.  Although you can use puppeteer for basic PDF generation, html-pdf-chrome has a richer and ever-growing feature set that will not be matched by puppeteer.  Below is a more in-depth comparison.
 
| puppeteer | html-pdf-chrome |
|-----------|-----------------|
| Requires Node.js v7.10+ | Requires Node.js v6+ |
| Can interact with Chrome to do many tasks | Laser-focused on generating PDFs and other images |
| Can listen for page render completion a few ways before generating a PDF | Can listen many ways (and more are to be added!) |
| Takes in Chrome-specific parameters for generation | Currently takes in Chrome parameters but plans to expand |
| No such feature or plan | Custom headers/footers for each printed page (planned) |
| Generates PDF to a raw buffer or file | Can save to raw buffer, file, base64 string, and stream |
