### ISSUE TITLE
setting up pm2

### ISSUE THREAD

**Issue by artknight** [westy92/html-pdf-chrome#360]
When setting up pm2 on ubuntu 20.04 I had to add `--no-sandbox` to the params to make it work. 

Hope this helps

**Comment by adhil-bit** [comment]
> When setting up pm2 on ubuntu 20.04 I had to add `--no-sandbox` to the params to make it work.
> 
> Hope this helps

thanks how can i add args can u pls give an example...

**Comment by artknight** [comment]
@adhil-bit all you have to do is add it to the general params you are already setting. Look at the bottom of the example below

Ex.
```
pm2 start google-chrome \
  --interpreter none \
  -- \
  --headless \
  --disable-gpu \
  --disable-translate \
  --disable-extensions \
  --disable-background-networking \
  --safebrowsing-disable-auto-update \
  --disable-sync \
  --metrics-recording-only \
  --disable-default-apps \
  --no-first-run \
  --mute-audio \
  --hide-scrollbars \
  --remote-debugging-port=<port goes here>
  --no-sandbox
```

**Comment by adhil-bit** [comment]
Thanks alot bro.. Worked for me...

**Comment by westy92** [comment]
Thank you @artknight!
