### ISSUE TITLE
Change return type of toStream() to Readable

### ISSUE THREAD

**Issue by ervinoro** [westy92/html-pdf-chrome#368]
It is actually a readable ( https://github.com/westy92/html-pdf-chrome/blob/master/src/CreateResult.ts#L90 ).

Having it typed as Stream means it is error, for example, when using Nest.js [StreamableFile](https://docs.nestjs.com/techniques/streaming-files):
```
Argument of type 'Stream' is not assignable to parameter of type 'Readable'.
  Type 'Stream' is missing the following properties from type 'Readable': readableAborted, readable, readableDidRead, readableEncoding, and 21 more.
```

**Comment by westy92** [comment]
According to the [typings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/stream.d.ts#L52), `class Readable extends Stream`, therefore `Readable` _is a_ `Stream`.

Could you please provide a minimal reproducible example?

**Comment by ervinoro** [comment]
Every Readable is a Stream, but not every Stream is a Readable. You can look at the example I provided from Nest.js, where the constructor for StreamableFile requires a Readable (for obvious reasons: it needs to read from the stream). It is a type error to pass a Stream to the constructor (because not every Stream is a Readable, and passing a non-readable stream is obviously nonsense). In reality it's unnecessary, because toStream will always return a Readable, therefore typing it as Readable would allow the result to be passed into the StreamableFile constructor without type errors.

**Comment by westy92** [comment]
Fixed in https://github.com/westy92/html-pdf-chrome/releases/tag/v0.8.4
