### ISSUE TITLE
ES6 code issue

### ISSUE THREAD

**Issue by Tin-Nguyen** [westy92/html-pdf-chrome#5]
I got the issue when I start my node server

```javascript
...../node_modules/html-pdf-chrome/lib/src/index.js:55
                    const { Page } = client;
```

It seems like the component cannot be compiled by itself Any ideas to have a fix on this?

**Comment by westy92** [comment]
What version of Node.js are you using?

**Comment by Tin-Nguyen** [comment]
oh I fixed it by upgrading to newer version of node. thanks
