### ISSUE TITLE
Emoji not rendered

### ISSUE THREAD

**Issue by GautierT** [westy92/html-pdf-chrome#54]
Hi. 
Thanks for this awesome package!
When i use it locally with emoji in HTML, the emoji are rendered. 
But when i tried to render the same HTML to PDF on heroku the emoji are replaced by square or weird code : ðŸš€.

Any idea why ?

Thanks a lot.

**Comment by westy92** [comment]
Most likely the system is missing a font capable of displaying the emoji.
Start looking for one here: https://graphicdesign.stackexchange.com/questions/31625/are-there-any-free-emoji-fonts

**Comment by GautierT** [comment]
Thanks a lot @westy92 !
I added a emoji ttf files in a .fonts folder at the root of my project and it's working.
