### ISSUE TITLE
Set Cookie

### ISSUE THREAD

**Issue by vidaldiego** [westy92/html-pdf-chrome#58]
Is there any way of setting cookies?

Thanks!

**Comment by westy92** [comment]
It looks like this is functionality that [can be added](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookie).

**Comment by westy92** [comment]
You can now set cookies during PDF generation:

```typescript
      const options: HtmlPdf.CreateOptions = {
        port,
        cookies: [
          {
            name: 'status',
            value: 'Passed!',
            domain: 'westy92.github.io',
          },
        ],
      };
```

Full options here: https://github.com/westy92/html-pdf-chrome/blob/0035606f229f98c476aef9ed7a0c9d1ccefc7ce8/src/typings/chrome/Network.ts#L3-L83
