### ISSUE TITLE
ability to specify host

### ISSUE THREAD

**Issue by tomasc** [westy92/html-pdf-chrome#7]
Useful when running Chrome in a separate Docker container.

I tried to hack it in (https://github.com/tomasc/html-pdf-chrome/commit/966ef4b0e6896c5cb33740e4f3481c035c2e2b0e), but not familiar with JS development so not sure how to update tests etc. in order to make proper PR.

**Comment by tomasc** [comment]
Thank you!

**Comment by westy92** [comment]
You're welcome.  I'm pushing off the release until I can finish up the other feature request.  For now, you should be able to use the specific commit hash in your project.

**Comment by westy92** [comment]
Released in v0.2.0!

**Comment by tomasc** [comment]
🎉
