### ISSUE TITLE
Support getting errors from the webpage

### ISSUE THREAD

**Issue by Pajn** [westy92/html-pdf-chrome#88]
It would be helpful if there were a way to get errors from the webpage, just a string of what is printed in the console (including exceptions).

I have not looked into the API chrome exports so it might be infeasable but if it isn't I think it would be a nice addition. The primary usecase would be, if the CompletionTrigger times out, the application would fetch the webpage errors so it can be debugged. For example a `getConsoleOutput(): Promise<string>` on `CreateResult`

**Comment by westy92** [comment]
Great idea!  This looks possible with [Runtime.consoleAPICalled](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-consoleAPICalled).

**Comment by westy92** [comment]
You can now attach callbacks to receive console messages and unhandled exceptions:
```typescript
const options: HtmlPdf.CreateOptions = {
    port,
    runtimeConsoleHandler: (event: Runtime.ChromeConsoleApiMessage) => { console.log(event); },
    runtimeExceptionHandler: (event: Runtime.ChromeRuntimeException) => { console.log(event); },
};
```

**Comment by vivex** [comment]
from where one can import RunTime ?
